on:
  push:
    branches:
      - 'master'
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release to Github
        uses: GoogleCloudPlatform/release-please-action@v1.3.0
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: tailwindcss-classnames

      - uses: actions/checkout@v2
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v1
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn install --frozen-lockfile
      - name: Generating Lib types
        run: yarn generate
      - name: Commit yarn generated files
        uses: stefanzweifel/git-auto-commit-action@v2.3.0
        with:
          commit_message: chore:generate library types
          branch: ${{ github.head_ref }}
        if: ${{ steps.release.outputs.release_created }}
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
